### ISSUE TITLE
"Draw Extra Borders" does not work

### ISSUE THREAD

**Issue by Racer911dash1** [passivestar/godot-minimal-theme#11] opened 2024-08-18 15:40 UTC
I've been setting up the theme as instructed, however I noticed that the "Draw Extra Borders" Option does not function at all. Nothing changes when it gets toggled on or off.
It is kind of a problem as it especially affects the File system window (Attached Image). 
![image](https://github.com/user-attachments/assets/dc826cb2-9b21-45dd-a9be-6f304272fc38)
![image](https://github.com/user-attachments/assets/8c32be30-35a3-4d34-b6cf-6d5b26670dd3)

**Comment by passivestar** [comment] 2024-08-18 16:15
Those panels not having any visual separation is not a border problem, it's a limitation of godot editor theming where all trees and item lists share the same styleboxes. So some lists not having visual boundaries where they appear to be needing them is a compromise I had to make the main window docks look as they do. It wasn't possible to fix in Godot 4.3. Hopefully 4.4 will be different

"Draw Extra Borders" shouldn't exist in the first place, Godot already has excessive borders by default, as far as accessibility goes I'd rather improve the visibility of UI elements by increasing contrast rather than drawing extra lines

**Comment by Racer911dash1** [comment] 2024-08-18 17:10
Oh okay, so is there an alternative solution? Or will I have to decide between a mild inconvenience or switching back to the default godot theme?

**Comment by passivestar** [comment] 2024-08-18 17:19
No solution yet. It's a work in progress and there are more things that are broken because they are simply unthemable. I fixed what I could for the release of 4.3 on the engine side, but there's still a lot of work to do

**Comment by passivestar** [comment] 2024-11-27 17:21
Support for "Draw Extra Borders" is not possible in a custom theme, but I made secondary lists support background panels on the engine side for visual separation (should be available when the next dev release of godot drops, you'll need to wait for a couple of weeks for it), so I believe this issue is now resolved. This is essentially a duplicate of https://github.com/passivestar/godot-minimal-theme/issues/8

**Closed by passivestar** 2024-11-27 17:21 UTC
